---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tglabs/app
    - /bin/rm -rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    # - /bin/bash /home/tglabs/deploy.sh 2>&1
