---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tglabs/app
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH
    - /home/tglabs/deploy.sh 2>&1
